export const FETCH_LOJAS_START = 'FETCH_LOJAS_START';
export const FETCH_LOJAS_SUCCESS = 'FETCH_LOJAS_SUCCESS';
export const FETCH_LOJAS_FAIL = 'FETCH_LOJAS_FAIL';

export const UPDATE_LOJA_START = 'UPDATE_LOJA_START';
export const UPDATE_LOJA_SUCCESS = 'UPDATE_LOJA_SUCCESS';
export const UPDATE_LOJA_FAIL = 'UPDATE_LOJA_FAIL';