export const FETCH_LOJAS_START = 'FETCH_LOJAS_START';
export const FETCH_LOJAS_SUCCESS = 'FETCH_LOJAS_SUCCESS';
export const FETCH_LOJAS_FAIL = 'FETCH_LOJAS_FAIL';

export const FETCH_USUARIOS_START = "FETCH_USUARIOS_START";
export const FETCH_USUARIOS_SUCCESS = "FETCH_USUARIOS_SUCCESS";
export const FETCH_USUARIOS_FAIL = "FETCH_USUARIOS_FAIL";